Vagrant.configure("2") do |config|

  # penultimate debian
  config.vm.box = "debian/bookworm64"

  # hardware allocation
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  # sharing the project root with VMs
  config.vm.synced_folder "./config", "/share"

  # server
  config.vm.define "rdel-aguS" do |server|
    server.vm.hostname = "rdel-aguS"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "rdel-aguS"
    end
    
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "./scripts/server.sh", args: ['192.168.56.110']
  end
end
