apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: myapp-helm-chart
    repoURL: 'https://github.com/POLROTY/rpol-k3d-argo/'
    targetRevision: master
  sources: []
  syncPolicy:
    automated:
      prune: false
      selfHeal: true